server:
  port: 8770
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 数据源配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    dirver-class-name: com.mysql.jdbcDrive
#zipkin:
#  storage:
#    type: mysql