server:
  port: 8770
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    dirver-class-name: com.mysql.jdbcDrive
zipkin:
  storage:
    type: mysql