server:
  port: 8772
#      开启断路器
feign:
  hystrix:
    enabled: true

spring:
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage:1.0
  multipart:
    max-file-size: 100Mb
    max-request-size: 100Mb
    enabled : false
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  resources:
    static-locations: classpath:static/
