server:
  port: 8765
zuul:
  routes:
    stu-account:
      path: /stu-account/**
 #     serviceId: stu-account
    stu-authority:
      path: /stu-authority/**
#      serviceId: stu-authority
    stu-host:
      path: /stu-host/**
#      serviceId: stu-host
    stu-order:
      path: /stu-order/**
#      serviceId: stu-order
spring:
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage:1.0
#      spring boot admin 默认开启的节点
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
#关闭安全验证
management:
  security:
    enable: false
#    日志输出路径
logging:
  file: "logs/boot-admin-sample.log"
