server:
  port: 8765
#路由转发
zuul:
  routes:
    stu-account:
      path: /stu-account/**
 #     serviceId: stu-account
    stu-authority:
      path: /stu-authority/**
#      serviceId: stu-authority
    stu-host:
      path: /stu-host/**
#      serviceId: stu-host
    stu-order:
      path: /stu-order/**
#      serviceId: stu-order
#数据链路配置
spring:
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage:1.0
